// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDGCTqtGhhHv8gFB0GAbUODrEHqqR9VWQ',
    appId: '1:201152150760:web:5a7738946e0da330831d5d',
    messagingSenderId: '201152150760',
    projectId: 'flutter-auth-46464',
    authDomain: 'flutter-auth-46464.firebaseapp.com',
    storageBucket: 'flutter-auth-46464.appspot.com',
    measurementId: 'G-1YB2CEW9RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWSp0-oQ1M9FVUENa6R1VcM0o6LNGpew',
    appId: '1:201152150760:android:50b9c5c2e721d9ff831d5d',
    messagingSenderId: '201152150760',
    projectId: 'flutter-auth-46464',
    storageBucket: 'flutter-auth-46464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9vXp8SSJPfacQyEV2GjnO-5b4RjYUOtM',
    appId: '1:201152150760:ios:19496e4f81e1354c831d5d',
    messagingSenderId: '201152150760',
    projectId: 'flutter-auth-46464',
    storageBucket: 'flutter-auth-46464.appspot.com',
    iosClientId: '201152150760-o355hejuese8uokuekg8tblmsntfrtd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9vXp8SSJPfacQyEV2GjnO-5b4RjYUOtM',
    appId: '1:201152150760:ios:2133daed0ff6d7d2831d5d',
    messagingSenderId: '201152150760',
    projectId: 'flutter-auth-46464',
    storageBucket: 'flutter-auth-46464.appspot.com',
    iosClientId: '201152150760-kvnngi85ero6652fimejak6bl8t4ifh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice.RunnerTests',
  );
}
